name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies in backend
        working-directory: ./backend
        run: npm install
        
      - name: Run the tests
        working-directory: ./backend
        run: npm run test:ci
        env:
          NODE_ENV: test
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.TEST_MONGO_URI }}

      - name: Install dependencies in frontend
        working-directory: ./frontend
        run: npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build